name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The jobb was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Pull Request
        # You may pin to the exact commit or the version.
        # uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          # GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
          token: ${{ github.token }} # optional, default is ${{ github.token }}
          # Relative path under $GITHUB_WORKSPACE to the repository. Defaults to $GITHUB_WORKSPACE.

          #path: $GITHUB_WORKSPACE # optional
          # The message to use when committing changes.
          commit-message: Create new PR # optional, default is [create-pull-request] automated change
          # The pull request branch name.
          branch: main # optional, default is create-pull-request/patch
          # The pull request base branch. Defaults to the branch checked out in the workflow.

          base: tranducduong1994-patch-1 # optional

          # The title of the pull request.
          title: Auto create a PR # optional, default is Changes by create-pull-request action
          # The body of the pull request.
          body: Body auto # optional, default is Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          
          # A comma or newline separated list of reviewers (GitHub usernames) to request a review from.
          reviewers: tranducduong1994 # optional
          # A comma or newline separated list of GitHub teams to request a review from. Note that a `repo` scoped Personal Access Token (PAT) may be required.
      - run: echo "🍏 This job's status is ${{ job.status }}."
